<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Asynchronous JavaScript</title>
</head>
<body>
    <h1>Asynchronous JavaScript</h1>
    <script>
        /*
        const second = () => {
            setTimeout(() => {
                console.log('Async Hey there');
            }, 2000);
        }

        const first = () => {
            console.log('Hey there');
            second();
            console.log('The end');
        }

        first();
        */



        /*
        function getRecipe() {
            setTimeout(() => {
                const recipeID = [523, 883, 432, 974];
                console.log(recipeID);

                setTimeout(id=> {
                    const recipe = {title: 'Fresh tomato pasta', publisher:'Jonas'};
                    console.log(`${id}: ${recipe.title}`);

                    setTimeout(publisher =>{
                        const recipe2 = {title: 'Italian Pizza', publisher: 'Jonas'};
                        console.log(recipe);
                    },1500, recipe.publisher);
                    
                }, 1500, recipeID[2]);

            }, 1500);

        }

        getRecipe();
        */


        /*
        // Produce promise
        // into the promise, we pass in a function called the executor, which is a function that will be immediately called once the promise is created.
        // the executor function takes in two arguments, which are the resolve and reject callback functions.
        // the executor function is used to inform the promise whether the event it is handling was successful or not.
        // If it was successful we're gonna call the resolve function, and if not we call the reject function.
        const getIDs = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve([523, 883, 432, 974]); // calling the resolve function will basically mark the promise as fullfilled. so as succeccful.
                                               // if we use the reject function we basically mark the promise as rejected.
            }, 1500);
        });

        // in the getRecipe function we pass in recID, so the recipe ID, which we then pass into this setTimeout and so then it will become, ID
        // and inside the callback function we use ID in resolve().
        const getRecipe = recID => {
            return new Promise((resolve, reject) => {
                setTimeout(ID => {
                    const recipe = {title: 'Fresh tomato pasta', publisher:'Jonas'};
                    resolve(`${ID}: ${recipe.title}`);
                }, 1500, recID);
            });
        };

        const getRelated = publisher => {
            return new Promise((resolve, reject) => {
                setTimeout(pub => {
                    const recipe = {title: 'Italian Pizza', publisher: 'Jonas'};
                    resolve(`${pub}: ${recipe.title}`);
                }, 1500, publisher);
            });
        };

        // // Consume promise
        // getIDs
        // // the 'then' method allows us to add an event handler for the case that the promise is fullfilled. which means that there is a result.
        // .then(IDs => { // this argument here will be the result of the successful promise. in this case [523, 883, 432, 974].
        //     console.log(IDs);
        //     return getRecipe(IDs[2]); // returns a promise
        // })
        // .then(recipe => { // we can add the next then to handle the result of that resolved promise
        //     console.log(recipe);
        //     return getRelated('Jonas Schmedtmann');
        // })
        // .then(recipe => {
        //     console.log(recipe);
        // })

        // // the 'catch' method allows us to add an handler for the case that the promise gets rejected. so that an error happened.
        // .catch(error => {
        //     console.log('Error!!');
        // });


        // async, await
        // was designed for us to consume promises, not to produce them

        // async function : one that keeps running in the background. ALWAYS automatically returns a promise.
        // await can only be used inside a async function.
        async function getRecipesAW() {
            const IDs = await getIDs; // consume our first promise getIDs, 'await' will stop the code from executing until the promise is fulfilled.
                                     // if the promise is resolved, then the value of that await expression is the resolved value of the promise. which is then assigned to the IDs variable.
            console.log(IDs);
            const recipe = await getRecipe(IDs[2]);
            console.log(recipe);
            const related = await getRelated('Jonas Schmedtmann');
            console.log(related);

            return recipe;
        }



        // this doesnt work because, getRecipesAW function runs asynchronously in the background
        // so by the time we try console log this getRecipesAW function is still running in the background. still doing its job.
        // so we only see the result as : Promise [<pendings>] : meaning, it's a promise but we dont have any results yet.
        // const rec = getRecipesAW(); // this code runs synchronously.
        // console.log(rec); // this code runs synchronously.



        // async function automatically returns a promise with the resolved value of recipe.
        // so we can now use 'then' in which we pass a callback function where the argument is the resolved value of the promise.
        getRecipesAW().then(result => console.log(`${result} is the best ever!`));
        */




        function getweather(woeid) {
            fetch(`https://cors-anywhere.herokuapp.com/https://www.metaweather.com/api/location/${woeid}/`) // fetch api gets our data and returns a promise
            .then(result => {
                //console.log(result);
                return result.json(); // will return a promise. because it happens asynchronously in the background.
            })
            .then(data => {
                //console.log(data);
                const today = data.consolidated_weather[0];
                console.log(`Temperatures today in ${data.title} stay between ${today.min_temp} and ${today.max_temp}.`);
            })
            .catch(error => console.log(error));
        }

        getweather(2487956);
        getweather(44418);





        async function getWeatherAW(woeid) {
            try {
                const result = await fetch(`https://cors-anywhere.herokuapp.com/https://www.metaweather.com/api/location/${woeid}/`);
                const data = await result.json();
                const tomorrow = data.consolidated_weather[1];
                console.log(`Temperatures tomorrow in ${data.title} stay between ${tomorrow.min_temp} and ${tomorrow.max_temp}.`);
                return data; //what we return from a async function will be the resolved value of the promise that this function returns
            } catch(error) {
                alert(error);
            }
        }
        getWeatherAW(2487956);
        let dataLondon;
        getWeatherAW(44418).then(data => {
            dataLondon = data;
            console.log(dataLondon);
        });



    </script>
</body>
</html>












